export const TEST_ID = {
  헤더: 'header',
  '헤더 이미지': 'waffle-logo',
  제목: 'header-title',
  '리뷰 목록': 'review-list',
  '우하단 녹색 버튼': 'write-review',
  '리뷰 작성 모달': 'write-review-modal',
  '리뷰 작성 모달 작성 버튼': 'submit-review',
  '리뷰 작성 모달 취소 버튼': 'cancel-review',
  '리뷰 작성 모달 이미지 인풋': 'image-input',
  '리뷰 작성 모달 과자이름 인풋': 'name-input',
  '리뷰 작성 모달 과자이름 오류 메시지': 'name-input-message',
  '리뷰 작성 모달 평점 인풋': 'rating-input',
  '리뷰 작성 모달 평점 오류 메시지': 'rating-input-message',
  '리뷰 작성 모달 내용 인풋': 'content-input',
  '리뷰 작성 모달 내용 오류 메시지': 'content-input-message',
  리뷰: 'review',
  '리뷰 수정 버튼': 'edit-review',
  '리뷰 수정 인풋': 'edit-review-content-input',
  '리뷰 수정 저장 버튼': 'edit-review-save',
  '리뷰 수정 취소 버튼': 'edit-review-cancel',
  '리뷰 삭제 버튼': 'delete-review',
  '리뷰 삭제 모달 취소 버튼': 'delete-review-cancel',
  '리뷰 삭제 모달 삭제 버튼': 'delete-review-delete',
};
