# Generated by Django 4.2.6 on 2023-11-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "content",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("comments", models.ManyToManyField(to="blog.comment")),
                ("posts", models.ManyToManyField(to="blog.post")),
            ],
        ),
    ]
